// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4HEn9BxEMhpKRnCOWCThpBHMqoV9DjRQ',
    appId: '1:994190058581:android:e20ad9d570af54daf560dc',
    messagingSenderId: '994190058581',
    projectId: 'hello-bible-plus',
    storageBucket: 'hello-bible-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogY9YjugwQUCALZL2sF_wBBt6nSTNsLo',
    appId: '1:994190058581:ios:0fa4c82ce34d2cc6f560dc',
    messagingSenderId: '994190058581',
    projectId: 'hello-bible-plus',
    storageBucket: 'hello-bible-plus.appspot.com',
    androidClientId: '994190058581-9q8njd54g553b6fgb35mbr4oq1pb9sf2.apps.googleusercontent.com',
    iosClientId: '994190058581-dfqg6r9qac823ivv8gut94bs2t6ojpq9.apps.googleusercontent.com',
    iosBundleId: 'com.myagency.gpt',
  );
}
